general {
    lock_cmd = omarchy-system-lock
    before_sleep_cmd = OMARCHY_LOCK_ONLY=true omarchy-system-lock
    after_sleep_cmd = sleep 1 && omarchy-system-wake
    inhibit_sleep = 3
}

listener {
    timeout = 900
    on-timeout = pidof hyprlock || omarchy-launch-screensaver
}

listener {
    timeout = 1200
    on-timeout = OMARCHY_LOCK_ONLY=true omarchy-system-lock
    on-resume = omarchy-system-wake
}

listener {
    timeout = 1800
    on-timeout = omarchy-brightness-keyboard off
    on-resume = omarchy-brightness-keyboard restore
}

listener {
    timeout = 1800
    on-timeout = omarchy-brightness-display off
    on-resume = omarchy-system-wake
}
