$activeBorderColor = rgba(8a8588ee) rgba(e2dddcee)
$inactiveBorderColor = rgba(584e51aa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
