$color = rgba(16, 19, 21, 1)
$inner_color = rgba(16, 19, 21, 1)
$outer_color = rgba(121, 129, 134, 1)
$font_color = rgba(202, 204, 204, 1)
$placeholder_color = rgba(202, 204, 204, 0.7)
$check_color = rgba(52, 61, 65, 1)
