$activeBorderColor = rgba(798186ee) rgba(caccccee)
$inactiveBorderColor = rgb(1e1e1e)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
}
